spring.application.name=ai-service
server.port=${PORT:8086}

farm.service.url=${FARM_SERVICE_URL:http://localhost:8082}
crop.service.url=${CROP_SERVICE_URL:http://localhost:8083}
weather.service.url=${WEATHER_SERVICE_URL:http://localhost:8084}
user.service.url=${USER_SERVICE_URL:http://localhost:8081}

python.ai.url=${PYTHON_AI_URL:http://localhost:5000}